#!/bin/zsh

REPO_URL="https://github.com/wycomco/misty.git"
TMP_DIR="/var/tmp/misty_pkgbuild"
ORIGINAL_DIR=$(pwd)

if [ -d "$TMP_DIR" ]; then
  echo "Found previously cloned repo in $TMP_DIR, deleting ..."
  rm -rf "$TMP_DIR"
fi

git clone "$REPO_URL" "$TMP_DIR"
if [ $? -ne 0 ]; then
  echo "Failed to clone repository."
  exit 1
fi

cd "$TMP_DIR" || { echo "Failed to cd into $TMP_DIR"; exit 1; }

#VERSION=$(git describe --tags --abbrev=0)
#echo "Current version of misty is $VERSION"
#echo "Replacing version in build-info.plist..."
#sed -E -i '' "s/[0-9]+.[0-9]+.[0-9]+/${VERSION}/g" misty/build-info.plist

munkipkg misty
if [ $? -ne 0 ]; then
  echo "munkipkg failed."
  cd "$ORIGINAL_DIR"  # Return to original directory
  exit 1
fi

open misty/build
cd "$ORIGINAL_DIR"

exit 0

