#!/bin/zsh

config_file="/var/root/misty/usr/config.txt"
currentUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )
log_file="/var/log/misty.log"
Base_Path="/var/root/misty"
Template="$Base_Path/skel"

# Check if config file already exists
if [[ -f "$config_file" ]]; then
  if grep -q '^munki_catalog_13="' "$config_file"; then
    sed -i '' '/^munki_catalog_13="/d' "$config_file"
    echo "Removed 'munki_catalog_13' line in $config_file by installer." >> "$log_file"
  fi
  if ! grep -q '^munki_catalog_26="' "$config_file"; then
    # Add the 'munki_catalog_26="testing"' line after any line that starts with 'munki_catalog_15="'
    sed -i '' '/^munki_catalog_15="/a\
munki_catalog_26="testing"
' "$config_file"
    echo "Added 'munki_catalog_26=\"testing\"' line after 'munki_catalog_15' in $config_file by installer." >> "$log_file"
    sudo -u "$currentUser" osascript -e 'tell app "System Events" to display dialog "Added »munki_catalog_26=\"testing\"« line after »munki_catalog_15« in $config_file by installer." with title "misty Installer" buttons {"Got it"} default button "Got it"'
  fi
fi

if [ ! -L "/usr/local/bin/misty" ]; then
    ln -s "/usr/local/wycomco/misty" "/usr/local/bin/misty"
fi

# Remove legacy skel files if present
/bin/rm "$Template/pre_inserts_arm64"
/bin/rm "$Template/pre_inserts_x86_64"
# Condition to check if we come from 0.2.6 or prior
if [[ -f "$Base_Path/usr/localized_arm.txt" ]]; then
  /bin/mv "$Base_Path/usr/localized_arm.txt" "$Base_Path/usr/localized_arm_legacy.txt"
  /bin/mv "$Base_Path/usr/localized_stage_os.txt" "$Base_Path/usr/localized_stage_os_legacy.txt"
  /bin/mv "$Base_Path/usr/localized_startos.txt" "$Base_Path/usr/localized_startos_legacy.txt"
  cp "$Template/localized_preloader.txt" "$Template/localized_macos.txt" "$Base_Path/usr"
  sudo -u "$currentUser" osascript -e 'tell app "System Events" to display dialog "You need to update your localized files. Please see the CHANGELOG file of the misty project for further instructions on how to migrate in version 0.2.7 or later." with title "misty Installer" buttons {"Got it"} default button "Got it"'
fi

exit 0
